version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: maquillaje
      MYSQL_USER: juliana
      MYSQL_PASSWORD: juli12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: